# cicd.yaml – workflow-fil för projektet SecureApp
# This workflow will build the SecureApp project

name: SecureApp

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Restore dependencies (install Nuget packages)
      run: dotnet restore
      working-directory: .
      
    - name: Publish the project
      run: dotnet publish SecureApp.csproj -c Release -o /opt/SecureApp
      working-directory: .

    - name: Upload app artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: secureapp-artifacts
        path: /opt/SecureApp
  

          ...
  deploy:
      runs-on: self-hosted
      needs: build
  
      steps:
        - name: Download the artifacts from GitHub (from the build job)
          uses: actions/download-artifact@v4
          with:
            name: secureapp-artifacts
  
        - name: Stop the application service
          run: |
            sudo systemctl stop SecureApp.service || true
  
        - name: Deploy the application
          run: |
            sudo rm -rf /opt/SecureApp || true
            sudo mkdir -p /opt/SecureApp
            sudo cp -r ./publish/* /opt/SecureApp

        - name: Start the application service
          run: sudo systemctl start SecureApp.service
            
        - name: Publish the project
          run: dotnet publish SecureApp.csproj -c Release -o ./publish
          working-directory: .
  